---
- name: Validate Security with Nmap
  hosts: "loadbalancers_{{ ENV }}"
  gather_facts: false
  become: true

  tasks:
    - name: Ensure ENV is defined
      ansible.builtin.fail:
        msg: "You must pass the ENV variable (e.g. -e 'ENV=staging')"
      when: ENV is not defined

    - name: Collect IPs of webservers in environment
      set_fact:
        webservers_ips: "{{ groups['webservers_' + ENV] | map('extract', hostvars, 'private_ip') }}"

    - name: Display the public and private IPs of loadbalancer
      ansible.builtin.debug:
        msg: >-
          Running nmap from {{ ansible_host }} (public), 
          the configured private IP is {{ private_ip }}.
    - name: Show webservers IPs
      debug:
        var: webservers_ips

    - name: Scan open ports with Nmap on private IP
      command: "nmap -Pn -T4 --top-ports 20 --open {{ item }}"
      register: nmap_scan
      loop: "{{ webservers_ips }}"
      become: false

    - name: Print open ports per host
      debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ nmap_scan.results }}"
      loop_control:
        label: "{{ item.item }}"
